before_install: npm install -g grunt-cli
before_script:
  - npm prune
  - npm install
script:
  - grunt
  - npm run test:single
after_success:
  - npm run report-coverage

language: node_js
node_js:
  - "4.1"
sudo: false
cache:
  directories:
    - node_modules
